<a href="https://colab.research.google.com/github/raviyk/recommendersys/blob/movielens/Session_embed_1_text_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
print(tf.__version__)

2.3.0


In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [5]:
#test data
sentences = [
             'I like peanutbutter and jam.',
             'I love salads and soup.',
             'I hate broccoli.'
]

In [6]:
MAX_VOCAB_SIZE = 20000 #Oxford dictionary has 200k words, and most common words is ~3k i.e. it covers 95% of most text
tokenizer = Tokenizer(num_words=MAX_VOCAB_SIZE)
tokenizer.fit_on_texts(sentences)
sequences = tokenizer.texts_to_sequences(sentences)

In [8]:
print(sequences)

[[1, 3, 4, 2, 5], [1, 6, 7, 2, 8], [1, 9, 10]]


In [9]:
tokenizer.word_index

{'and': 2,
 'broccoli': 10,
 'hate': 9,
 'i': 1,
 'jam': 5,
 'like': 3,
 'love': 6,
 'peanutbutter': 4,
 'salads': 7,
 'soup': 8}

In [11]:
#use default values
data = pad_sequences(sequences)
print(data)

[[ 1  3  4  2  5]
 [ 1  6  7  2  8]
 [ 0  0  1  9 10]]


In [13]:
MAX_SEQ_LENGTH = 5

In [14]:
#use default values
data = pad_sequences(sequences, maxlen=MAX_SEQ_LENGTH)
print(data)

[[ 1  3  4  2  5]
 [ 1  6  7  2  8]
 [ 0  0  1  9 10]]


In [15]:
MAX_SEQ_LENGTH = 4

In [16]:
#use default values
data = pad_sequences(sequences, maxlen=MAX_SEQ_LENGTH)
print(data)

[[ 3  4  2  5]
 [ 6  7  2  8]
 [ 0  1  9 10]]


In [17]:
#use default values
data = pad_sequences(sequences, maxlen=MAX_SEQ_LENGTH, padding='post')
print(data)

[[ 3  4  2  5]
 [ 6  7  2  8]
 [ 1  9 10  0]]


In [18]:
#use default values
data = pad_sequences(sequences, maxlen=MAX_SEQ_LENGTH, padding='post', truncating='post')
print(data)

[[ 1  3  4  2]
 [ 1  6  7  2]
 [ 1  9 10  0]]
